In [7]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [8]:
iris = load_iris()

X = iris.data
y = iris.target

print("Features Shape :", X.shape)
print("Target Shape :", y.shape)

Features Shape : (150, 4)
Target Shape : (150,)

In [9]:
df = pd.DataFrame(X, columns=iris.feature_names)

df["Species"] = y

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training Samples :", len(X_train))
print("Testing Samples :", len(X_test))

Training Samples : 120
Testing Samples : 30

In [11]:
model = LogisticRegression(max_iter=200)

model.fit(X_train, y_train)

print("Model Training Completed")

Model Training Completed

In [13]:
y_pred = model.predict(X_test)

In [14]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy =", accuracy)

Accuracy = 1.0

In [15]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

In [16]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [17]:
scores = cross_val_score(
    model,
    X,
    y,
    cv=5
)

print("Cross Validation Scores")

print(scores)

Cross Validation Scores
[0.96666667 1.         0.93333333 0.96666667 1.        ]

In [18]:
print("Average Accuracy")

print(scores.mean())

Average Accuracy
0.9733333333333334

In [19]:
print("Standard Deviation")

print(scores.std())

Standard Deviation
0.02494438257849294

In [20]:
results = pd.DataFrame({
    "Fold":[1,2,3,4,5],
    "Accuracy":scores
})

results

   Fold  Accuracy
0     1  0.966667
1     2  1.000000
2     3  0.933333
3     4  0.966667
4     5  1.000000

In [21]:
print("="*50)

print("Train/Test Split Completed")

print("Cross Validation Completed")

print("Average CV Accuracy :", scores.mean())

print("="*50)

==================================================
Train/Test Split Completed
Cross Validation Completed
Average CV Accuracy : 0.9733333333333334
==================================================